# Generated by Django 4.2.4 on 2023-08-05 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
